"""Built-in tool surface — type-safe registry, execution engine + dynamic MCP."""

from coderai.core.tools.executor import ToolExecutor
from coderai.core.tools.registry import ToolRegistry, get_tool_registry
from coderai.core.tools.schema import (
    assert_supported_json_schema,
    define_tool,
    validate_json_schema_value,
)
from coderai.core.tools.types import (
    BackgroundProcessCompletion,
    ProcessTimeoutControl,
    ProcessTimeoutInfo,
    ToolAbortedError,
    ToolArgsError,
    ToolCall,
    ToolCallExecution,
    ToolCategory,
    ToolDefinition,
    ToolError,
    ToolExecutionContext,
    ToolExecutionError,
    ToolExecutionFollowUpMessage,
    ToolExecutionHooks,
    ToolExecutionResult,
    ToolNotFoundError,
    ToolOutputDefinition,
    ToolOutputError,
    ToolPresentationMode,
    ToolResult,
    ToolTimeoutError,
    ValidationError,
)

__all__ = [
    "BackgroundProcessCompletion",
    "ProcessTimeoutControl",
    "ProcessTimeoutInfo",
    "ToolAbortedError",
    "ToolArgsError",
    "ToolCall",
    "ToolCallExecution",
    "ToolCategory",
    "ToolDefinition",
    "ToolError",
    "ToolExecutionContext",
    "ToolExecutionError",
    "ToolExecutionFollowUpMessage",
    "ToolExecutionHooks",
    "ToolExecutionResult",
    "ToolExecutor",
    "ToolNotFoundError",
    "ToolOutputDefinition",
    "ToolOutputError",
    "ToolPresentationMode",
    "ToolRegistry",
    "ToolResult",
    "ToolTimeoutError",
    "ValidationError",
    "assert_supported_json_schema",
    "define_tool",
    "get_tool_registry",
    "validate_json_schema_value",
]
