"""Slash command catalog for /help."""

HELP_MENU_ENTRIES = [
    ("/help", "Open this command menu"),
    ("/model", "Open model picker · /model <name> · /model default <name>"),
    ("/plan", "Show current execution plan"),
    ("/clear", "Wipe conversation & context"),
    ("/compact", "Summarize long context"),
    ("/reasoning", "Open reasoning picker · /reasoning <high|medium|low|none>"),
    ("/yolo", "Toggle auto-approve for high-risk tools"),
    ("/allow-tool", "Always allow one tool for this session"),
    ("/disallow-tool", "Remove a per-session tool allowlist entry"),
    ("/allowed-tools", "List tools already allowlisted this session"),
    ("/verbose", "Toggle reasoning + expanded tool cards"),
    ("/agents", "Refresh the agents panel"),
    ("/persona", "List or switch persona"),
    ("/skills", "List workflows under .coderAI/skills/"),
    ("/show", "Reference info · type /show then a topic"),
    ("/think", "Reveal the latest hidden reasoning as a toast"),
    ("/search", "Search conversation transcript"),
    ("/code-search", "Search the codebase semantically"),
    ("/export", "Export session to markdown"),
    ("/copy", "Copy last assistant response (OSC-52)"),
    ("/theme", "Persist dark/light theme"),
    ("/undo", "Undo last tool action"),
    ("/tokens", "Show token usage, cost & context stats"),
    ("/context", "View pinned context files"),
    ("/exit", "Shut down the agent"),
]
