"""Tool inspection and generated documentation from authoritative definitions."""

from __future__ import annotations

import json
from typing import Any
from coderai.tools.legacy.types import ToolExecutionContext
from coderai.tools.legacy.policy import external_effects


def inspect_tools(
    registry: Any,
    context: ToolExecutionContext,
    *,
    options: dict[str, Any] | None = None,
    external_tools: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    options = options or {}
    effective = {
        d["function"]["name"]
        for d in registry.to_openai_schemas(context.session_id, options, external_tools)
    }
    tools = dict(registry._global_layer.tools)
    layer = registry._scoped_layers.get(context.session_id)
    if layer:
        tools.update(layer.tools)
    rows = []
    planning_conditions = {
        "bash": "Read-only OS sandbox; escalation unavailable",
        "pwsh": "Read-only OS sandbox; escalation unavailable",
        "write": "Exact session-owned plan file only",
        "edit": "Exact session-owned plan file only",
        "str_replace_editor": "command=view only",
        "goal": "action=status only",
        "Task": "mode=read_only only",
        "subagent": "mode=read_only only",
        "subagent_fork": "mode=read_only only",
    }
    for tool in tools.values():
        effect = tool.resolve_effects({})
        available = tool.name in effective
        reasons = []
        if not registry.admits(tool.name, context.session_id):
            reasons.append("Global or session restriction")
        elif not available:
            reasons.append("Role, preset, interaction, or model capability filter")
        condition = planning_conditions.get(tool.name) if context.plan_mode else None
        if condition:
            reasons.append(condition)
        elif context.plan_mode and effect not in {"read", "session"}:
            reasons.append("Effects are unavailable during planning")
        rows.append(
            {
                "name": tool.name,
                "available": available
                and (
                    not context.plan_mode or effect in {"read", "session"} or condition is not None
                ),
                "conditional": available and condition is not None,
                "source": tool.handler.__module__ if tool.handler else "builtin",
                "aliases": tool.aliases,
                "effects": effect,
                "invocation_effects": tool.name
                in {"goal", "str_replace_editor", "Task", "subagent", "subagent_fork"},
                "timeout_ms": tool.timeout_ms,
                "description": tool.description,
                "parameters": tool.runtime_schema(),
                "restrictions": reasons,
            }
        )
    for definition in external_tools or []:
        function = definition.get("function") or {}
        name = function.get("name", "")
        effect = external_effects(name, context)
        reasons = [] if name in effective else ["Global, session, role, or preset restriction"]
        if context.plan_mode and effect != "read":
            reasons.append("External effect policy does not declare a trusted read")
        rows.append(
            {
                "name": name,
                "available": name in effective and (not context.plan_mode or effect == "read"),
                "source": "external",
                "aliases": [],
                "effects": effect,
                "invocation_effects": False,
                "timeout_ms": None,
                "description": function.get("description", ""),
                "parameters": function.get("parameters", {}),
                "restrictions": reasons,
            }
        )
    return sorted(rows, key=lambda row: row["name"].lower())


def render_catalog(registry: Any) -> str:
    rows = inspect_tools(
        registry, ToolExecutionContext("catalog", "."), options={"childAgent": True}
    )
    lines = [
        "# Built-in tool catalog",
        "",
        "Generated by `scripts/tool_catalog.py`; schemas remain authoritative at runtime.",
        "",
        "Use `/tools` and `/tools <name>` for the effective session catalog. Effects can depend on arguments.",
        "",
        "| Tool | Aliases | Effects | Timeout (ms) | Source |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row['name']}` | {', '.join(row['aliases']) or '—'} | {row['effects']}{' (per invocation)' if row['invocation_effects'] else ''} | {row['timeout_ms'] or 'session default'} | `{row['source']}` |"
        )
    for row in rows:
        lines.extend(
            [
                "",
                f"## {row['name']}",
                "",
                row["description"],
                "",
                "```json",
                json.dumps(row["parameters"], indent=2, sort_keys=True),
                "```",
            ]
        )
    return "\n".join(lines) + "\n"
